{% set name = "ablog" %}
{% set version = "0.11.11" %}
{% set sha256 = "a236bc4302bf51c32b1e010fb2dd52461d26369ef8beff210532e69cd0d4d145" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - ablog = ablog.commands:ablog_main
  noarch: python

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools_scm
  run:
    - python >=3.10
    - sphinx >=6.2
    - invoke
    - docutils
    - python-dateutil
    - watchdog
    - feedgen
    - nbsphinx
    - pandoc
    - myst-parser
    - packaging
    - jinja2

test:
  requires:
    - git
    - alabaster
    - sphinx-automodapi
    - graphviz
    - make
    - pytest
  commands:
    - ablog --version
    - git clone --depth 1 https://github.com/sunpy/ablog
    - cd ablog
    - git switch -c v{{ version }}
    - pytest -p no:warnings --pyargs ablog
    - make tests

about:
  home: https://github.com/sunpy/ablog
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  summary: ABlog for blogging with Sphinx
  description: |
    A Sphinx extension that converts any documentation or personal website
    project into a full-fledged blog.
  doc_url: http://ablog.readthedocs.org
  dev_url: https://github.com/sunpy/ablog

extra:
  recipe-maintainers:
    - nabobalis
    - cadair
    - wtbarnes
