{% set name = "ablog" %}
{% set version = "0.10.3" %}
{% set sha256 = "20caf0c567e8b94f9a255467758ed847220df3490501d71c3cdfcddcbbec7860" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - ablog = ablog.commands:ablog_main

requirements:
  build:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - werkzeug <1.0.0
    - sphinx >=2.0
    - alabaster
    - invoke
    - python-dateutil
    - sphinx-automodapi
    - watchdog

test:
  requires:
    - git
    - nbsphin x<0.5.0
  commands:
    - ablog --version
    - git clone --depth 1 --branch v{{ version }} https://github.com/sunpy/ablog
    - cd ablog/docs
    - ablog build -T
    - ablog build -b latex -T -d .doctrees -w _latex
    - ablog build -T -b json
    - ablog build -T -b pickle

about:
  home: https://github.com/sunpy/ablog
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  summary: 'ABlog for blogging with Sphinx'
  description: |
    A Sphinx extension that converts any documentation or personal website
    project into a full-fledged blog.
  doc_url: http://ablog.readthedocs.org
  dev_url: https://github.com/sunpy/ablog

extra:
  recipe-maintainers:
    - nabobalis
    - cadair
