travis:
  secure:
    BINSTAR_TOKEN: cmG9BOIx7MTfVmm60bWrqwknmQsKImzUjtk0IlwpqmT63ASDWO3Jgv2Z/vNWvawnNtfdMwkBU63PWV2hwwRsS/zst+wgXFAzvCQkv+dBoom2cptpHMbsuJ3wpoUBsawfpUpKdJv0QBsauFzEoRsxVd0rHDYrGGxq1uf2ECmTNR1PklGvEWlw+Pia0ACTzTsxbtTBC3LFRLYZe+9k07d1cjFSzwWmqe145V1sEc2fcUHUyRTCxpodBfu/a87gobdALYBZRtH+8z0BMxEKYi1onzb7HM5KSsA3Zw8ZLg/LVjRzRk3lJV69A74uzvP/NBUzUw0+qlqHl/aBbiHAyYJKJwTLU/aryLcV0loOLQlAOnrTXJCXLt/5jkesGvFO0h221beZk0FvwfKrjt0cvJ2PzhmdzWhanhh49hYf6dPKmBdwIhgVR1h0EkoSZFiRjlFVYZOMiWNjGhEWlnzYOJoZ3I2+aJZFsc0sCQRgyXOBAfxXz1/wsGA3+0DCYEbxLou6w9K2+RyBOznJrqUmUV0C+Ntx0RiIz3v+89tz55EGgrI7ZlDsyZvHpJwgGz9pB8qNAzu6s//wLCHGXUMmfaEK0O1qKOTeiFb+N25xHhHfnZ3AkwvORBZosItVN1sm1jXsn5oltxTRMGybxLj3F9BZTnGVRH1RVb5/3qQOXkP4iFE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
