travis:
  secure:
    BINSTAR_TOKEN: GVwOTg9dGvgbHQ4QrqV1lOPSn+bPK9lBGvGNV+djhOhaemg7+f95RvQDULUK4aSrFGI3MH7P3j2j/vdVSJxCctGHNKcd/6+Kv9ql3cNXIIkbzC2XkfB/6ilgBg3V59xzDlh93cw9ApJ1ZrxfWFxrQybxjfmAij6kPJr+tMpk4F8R3VmBSLshdWDWRng0us933tPBUTeEj+FWdmOrhgeDQEK2EuF1PAAXlwP7rJZiH4FEsssll/e8g38n7/IRjRKl3DYnJEzBbVAXTQ9atDmQm7YIsV+R1f6zXU9ESXAoRHzPKja1CJofF+tCmBctpQqzXmwMx0sJFMUnw/UjDya7MDoo93Ovs1wEkMQvt3ssHsIIY2omUN2ZDqLdKhwP2VXFiBPAQ/wjpdOM2/B1iDDVN+eOKphYMeeUR4axycNTG55crn6eYYJrWvbPQWykImtFRzo8ttJ5dBgdtEDV4QZercAgA2sC48Ssr5OovL55cVkWYZ7uQ1fkTUQ/rssytm4Dn49nY8KD3Tcfl45qCx9lyqy/8l0gpw7Vlue+u4FsRVfa4TSkTkipAQqw+8HC3dDR3RG4nQG18g8rGayuIG7mNgWO4gjqNuJabfUrwF+QGBlss28lMTvBJCm0zBebeS5H9+2R0XfNuhaVCVgsUbdAu6FoTzBLsGvTsljpdA4kV68=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
